- platform: smartir
  name: Living Room AC
  unique_id: living_room_ac
  device_code: 1400
  controller_data: !secret broadlink_address
  temperature_sensor: sensor.weather_temperature
  #humidity_sensor:
  #power_sensor: binary_sensor.ac_power