homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.5.0/24
    #- type: legacy_api_password
    #  api_password: !secret http_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zagreb
# Customization file
  customize: !include customize.yaml
# Weather DarkSky setup
#   weather:
#   - platform: darksky
#      api_key: !secret darksky_api_key
#      mode: daily
# enable_debug:
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  login_attempts_threshold: 4


# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
ios:
person:
#   - name: Luka
#     id: djlujo
#     user_id: !secret user_id
#     device_trackers:
#       - device_tracker.lujo_iphone
      
# Sensors
sensor:
  # Weather prediction
  - platform: time_date
    display_options:
      - 'date'
      - 'time'
  - platform: yr
    name: Weather 
    monitored_conditions:
      - temperature
      - symbol
## Climate control custom component
smartir:
climate: !include climate.yaml
# Enables configuration UI
config:
# View all events in a logbook
logbook:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    homeassistant.components.media_player: critical
    homeassistant.core: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.http.ban: warning
# Rss feeds
feedreader:
  urls:
    - https://www.home-assistant.io/atom.xml
    - http://feeds.feedburner.com/RecentCommitsToSmartirmaster
  scan_interval:
    minutes: 30
  max_entries: 5
# HACS
hacs:
  token: !secret github_token
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
# Notifications
notify:
  - platform: ios
# Exposed entities for Google Home control
google_assistant: !include google_assistant.yaml
# UI grouping
group: !include groups.yaml
# Automations
automation: !include automations.yaml
# Home/Away Presence control
device_tracker: !include device_tracker.yaml
# Scripts
script: !include scripts.yaml
# UI Components
switch: !include_dir_merge_list switch
input_select: !include input_select.yaml
