---
# Xiaomi Thermometer 2
- platform: mitemp_bt
  # rounding: True
  # decimals: 1
  # period: 60
  # log_spikes: False
  # use_median: False
  active_scan: false
  extended_scan: true
  hci_interface: 0
  batt_entities: true
  # encryptors:
  #  'A4:C1:38:7F:00:93': '4c6e1cd9e833be6edc77898347c818a6'
  report_unknown: false
  sensor_names:
    "A4:C1:38:7F:00:93": "Livingroom"
  whitelist:
    - "A4:C1:38:7F:00:93"
# - platform: yr
#  name: Weather
#  monitored_conditions:
#    - temperature
#    - symbol
